variable "server_name" {
  type        = "string"
  description = "TODO"
}

variable "matrix_subdomain" {
  type        = "string"
  default     = "matrix"
  description = "TODO"
}

variable "chat_domain" {
  type        = "string"
  description = "TODO"
}

variable "region" {
  type        = "string"
  default     = "tor1"
  description = "the digital ocean region."
}

variable "link_preview" {
  type        = "string"
  default     = "false"
  description = "TODO"
}

variable "do_token" {
  type        = "string"
  description = "the digital ocean access token. Steps to generate can be found at the following link: https://www.digitalocean.com/docs/api/create-personal-access-token/"
}

variable "pub_key" {
  type        = "string"
  description = "the file containing your digital ocean public key."
}

variable "pvt_key" {
  type        = "string"
  description = "the file containing your digital ocean private key."
}

variable "ssh_fingerprint" {
  type        = "string"
  description = "can be generated by running the following command: ssh-keygen -E md5 -lf PUBLIC_KEY_FILE | awk '{print $2}' | sed  's/MD5://'"
}

variable "nginx_email" {
  type        = "string"
  description = "an email attached to the SSL certification provided by certbot/letsencrypt. If you manage to lose access to your server, or keys, THIS is the address that things will go to.r"
}
